name: Deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The ref to deploy'
        required: false
  push:
    branches:
      - ws-3.0.0
      - v*

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy maven packages to pkg.github
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Deploy
        shell: bash
        run: |
          ./mvnw -B versions:set -DnewVersion=${GITHUB_SHA::7}-SNAPSHOT -DgenerateBackupPoms=false
          ./mvnw -T2C --batch-mode -q --settings maven-settings.xml clean deploy \
                -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/whaleops/dolphinscheduler \
                -Dmaven.test.skip \
                -Dmaven.javadoc.skip \
                -Dmaven.site.skip=true \
                -Djacoco.skip=true \
                -Dspotless.apply.skip \
                -DretryFailedDeploymentCount=5
